---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - rc

- name: config line rc
  lineinfile:
    state: "{{'absent' if (item.state|default(True) == False) else 'present'}}"
    line: "{{item.name}}=\"{{item.value}}\" # Ansible: {{item.comment|default('')}}"
    regexp: "^{{item.name}}="
    dest: "{{item.path if not (item.path|default('') == '') else file_dst_rc_conf}}"
    create: True
  loop: "{{rc_config_all + rc_config_group + rc_config_host}}"
  tags:
    - rc
