---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_version}}.yml"
        - 'vars/main.yml'
  tags:
    - rest_server

- name: status rest_server
  command: "{{command_cmd_status_rest_server}}"
  register: register_status_rest_server
  changed_when: (register_status_rest_server.rc > 1)
  failed_when: (register_status_rest_server.rc > 1)
  check_mode: False
  tags:
    - rest_server

- name: disable rest_server
  command: "{{command_cmd_disable_rest_server}}"
  check_mode: False
  when: register_status_rest_server.rc == 0
  tags:
    - rest_server

- name: check rest_server
  command: "{{command_cmd_check_rest_server}}"
  register: register_check_rest_server
  changed_when: (register_check_rest_server.rc > 1)
  failed_when: (register_check_rest_server.rc > 1)
  check_mode: False
  tags:
    - rest_server

- name: stop rest_server
  command: "{{command_cmd_stop_rest_server}}"
  check_mode: False
  when: register_check_rest_server.rc == 0
  tags:
    - rest_server

- name: remove user rest-server
  user:
    state: absent
    name: "{{user_name_rest_server}}"
    remove: "{{user_home_remove_rest_server}}"
    force: "{{user_home_force_rest_server}}"
  tags:
    - rest_server

- name: remove group rest-server
  group:
    state: absent
    name: "{{group_name_rest_server}}"
  tags:
    - rest_server

- name: remove file rest_server.service
  file:
    state: absent
    path: "{{file_dst_rest_server_service}}"
  tags:
    - rest_server

- name: remove file rest-server
  file:
    state: absent
    path: "{{file_creates_rest_server}}"
  tags:
    - rest_server

- name: remove file rest-server.tar.gz
  file:
    state: absent
    path: "{{file_dst_rest_server_tar_gz}}"
  tags:
    - rest_server

- name: remove file rest_server.cfg
  file:
    state: absent
    path: "{{file_dst_rest_server_cfg}}"
  notify: reload monit
  tags:
    - rest_server

- name: config file includes.conf
  lineinfile:
    state: absent
    regexp: "{{file_regexp_includes_conf}}"
    dest: "{{file_dst_includes_conf}}"
    create: True
  notify:
    - validate pf
    - reload pf
  tags:
    - rest_server

- name: remove file rest_server.pf
  file:
    state: absent
    path: "{{file_dst_rest_server_pf}}"
  notify: reload pf
  tags:
    - rest_server

- name: remove file rest-server_etc.dir
  file:
    state: absent
    path: "{{file_dst_rest_server_etc_dir}}"
  tags:
    - rest_server
