---

- name: assert operating system family and version
  block:

    - name: import tasks install
      import_tasks: install.yml
      when: not (ca_certificate_state is match('false|no|remove|quiesce|inactive'))

    - name: import tasks config
      import_tasks: config.yml
      when: not (ca_certificate_state is match('false|no|remove|quiesce|inactive'))

    - name: import tasks remove
      import_tasks: remove.yml
      when: (ca_certificate_state is match('false|no|remove'))

  when: ((ansible_os_family == 'OpenBSD') and (ansible_distribution_version is match('7\.7|7\.8')))
  tags:
    - ca_certificate
